/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Colaborador;

import Modelo.C_Persona;
import javax.swing.*;

/**
 *
 * @author Alberto
 */
public class PanelColaboradorDatos extends javax.swing.JPanel {
	java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form PanelColaboradorDatos
     */
    public PanelColaboradorDatos() {
        initComponents();
		labelError.setVisible(false);
		labelErrorColaboracion.setVisible(false);
		btHacerSocio.setVisible(false);
    }
	
	
	public JButton getBtBorrarDatosColaborador() {
		return btLimpiarDatosColaborador;
	}

	public JButton getBtGuardarDatosColaborador() {
		return btGuardarDatosColaborador;
	}
	
	public void setTextLabelError (String text) {
		labelError.setText(text);
		labelError.setVisible(true);
	}
	
	public JTextField getTextNombre(){
		return jTextNombre;
	}
    public JTextField getTextApellidos(){
		return jTextApellidos;
	}
    public JTextField getTextDNI(){
		return jTextDNI;
	}
    public JTextField getTextEmail(){
        return jTextEmail;
    }
        
	public JFormattedTextField getTextFN(){
		return jFormattedTextFechaNacimiento;
	}
	public char getSexo(){
		if(radioSexoMasculinoSocio.isSelected())
			return 'H';
		else
			return 'M';

	}
	public JTextField getTextLocalidad(){
			return jTextLocalidad;
	}

	public JTextField getTextProvincia(){
			return jTextProvincia;
	}        

	public JTextField getTextDomicilio(){
			return jTextDomicilio;
	}

	public JTextField getTextCP(){
			return jTextCP;
	}

	public JTextField getTextTelfFijo(){
			return jTextTelefono;
	}

	public JTextField getTextTelMovil(){
			return jTextMovil;
	}
	
	public void escribirColaboradorDatos(String[] datos){

			jTextNombre.setText(datos[0]);
			jTextApellidos.setText(datos[1]);
			jTextDNI.setText(datos[2]);
			jTextEmail.setText(datos[3]);
			jFormattedTextFechaNacimiento.setText(datos[4]);
			if(datos[5].equals("M"))
				radioSexoFemeninoSocio.setSelected(true);
			else
				radioSexoMasculinoSocio.setSelected(true);
			jTextLocalidad.setText(datos[6]);
			jTextProvincia.setText(datos[7]);
			jTextDomicilio.setText(datos[8]);
			jTextCP.setText(datos[9]);  
			jTextTelefono.setText(datos[10]);
			jTextMovil.setText(datos[11]);
			labelError.setVisible(false);
	}
	public void modificarColaborador(C_Persona persona){

			jTextNombre.setText(persona.getNombre());
			jTextApellidos.setText(persona.getApellidos());
			jTextDNI.setText(persona.getDNI() );
			jTextEmail.setText(persona.getEmail());
			jFormattedTextFechaNacimiento.setText(sdf.format(persona.getFechaDeNacimiento()));
			if(persona.getSexo()=='M')
				radioSexoFemeninoSocio.setSelected(true);
			else
				radioSexoMasculinoSocio.setSelected(true);
			jTextLocalidad.setText(persona.getLocalidad());
			jTextProvincia.setText(persona.getProvincia());
			jTextDomicilio.setText(persona.getDireccion());
			jTextCP.setText(persona.getCP());  
			jTextTelefono.setText(persona.getTelefonoFijo());
			jTextMovil.setText(persona.getTelefonoMovil());
			labelError.setVisible(false);
	}
	
	public JTabbedPane getJtabbedPaneColaborador(){
		return jTabbedPaneColaboradores;
	}
	public JButton getHacerSocio(){
		return btHacerSocio;
	}
	
	public JButton getBtEliminarColaboracion(){
		return btEliminarColaborador;
	}
	public JButton getBtBuscarColaboraciones(){
		return btBuscarColaboraciones;
	}
	public JButton getBtGuardarColaboracion(){
		return btGuardarColaboracionColaborador;
	}
	
	public JTextField getTextCantidad(){
		return JtextCantidadColaborador;
	}
	public JTextField getTextConcepto(){
		return JtextConceptoColaborador;
	}
	
	public JFormattedTextField getTextFecha(){
		return jFormattedTextFecha;
	}
	public JFormattedTextField getTextFechaInicio(){
		return jFormattedTextFechaInicio;
	}
	public JFormattedTextField getTextFechaFinal(){
		return jFormattedTextFechaFinal;
	}
	public void setTextLabelErrorColaboracion(String cadena){
		labelErrorColaboracion.setText(cadena);
		labelErrorColaboracion.setVisible(true);
	}
	
	public void setTextLabelErrorColaboracionVisible(Boolean bol){
		labelErrorColaboracion.setVisible(bol);
	}
	
	public JTable getTablaColaboraciones(){
		return JtableColaboracionesColaborador;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jTabbedPaneColaboradores = new javax.swing.JTabbedPane();
        PanelDatosColaborador = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        radioSexoFemeninoSocio = new javax.swing.JRadioButton();
        label17 = new javax.swing.JLabel();
        btGuardarDatosColaborador = new javax.swing.JButton();
        btLimpiarDatosColaborador = new javax.swing.JButton();
        radioSexoMasculinoSocio = new javax.swing.JRadioButton();
        labelError = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextDomicilio = new javax.swing.JTextField();
        jTextLocalidad = new javax.swing.JTextField();
        jTextCP = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextMovil = new javax.swing.JTextField();
        jTextProvincia = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jFormattedTextFechaNacimiento = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Localidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btHacerSocio = new javax.swing.JButton();
        PanelColaboracionesColaborador = new javax.swing.JPanel();
        label43 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        JtableColaboracionesColaborador = new javax.swing.JTable();
        label44 = new javax.swing.JLabel();
        label45 = new javax.swing.JLabel();
        JtextCantidadColaborador = new javax.swing.JTextField();
        label46 = new javax.swing.JLabel();
        JtextConceptoColaborador = new javax.swing.JTextField();
        label47 = new javax.swing.JLabel();
        btGuardarColaboracionColaborador = new javax.swing.JButton();
        btBuscarColaboraciones = new javax.swing.JButton();
        btEliminarColaborador = new javax.swing.JButton();
        jFormattedTextFecha = new javax.swing.JFormattedTextField();
        jFormattedTextFechaInicio = new javax.swing.JFormattedTextField();
        jFormattedTextFechaFinal = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelErrorColaboracion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPaneColaboradores.setBackground(new java.awt.Color(255, 255, 255));

        PanelDatosColaborador.setBackground(new java.awt.Color(255, 255, 255));

        label7.setForeground(new java.awt.Color(255, 51, 51));
        label7.setText("Datos personales");

        label14.setText("de");

        radioSexoFemeninoSocio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(radioSexoFemeninoSocio);
        radioSexoFemeninoSocio.setText("Mujer");

        label17.setForeground(new java.awt.Color(255, 0, 0));
        label17.setText("Datos de contacto");

        btGuardarDatosColaborador.setBackground(new java.awt.Color(255, 255, 255));
        btGuardarDatosColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/guardar.png"))); // NOI18N
        btGuardarDatosColaborador.setBorder(null);

        btLimpiarDatosColaborador.setBackground(new java.awt.Color(255, 255, 255));
        btLimpiarDatosColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/limpiar.png"))); // NOI18N
        btLimpiarDatosColaborador.setBorder(null);

        radioSexoMasculinoSocio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(radioSexoMasculinoSocio);
        radioSexoMasculinoSocio.setSelected(true);
        radioSexoMasculinoSocio.setText("Hombre");
        radioSexoMasculinoSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelError.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 51, 51));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelError.setText("Error");

        jFormattedTextFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel1.setText("Nombre");

        jLabel2.setText("DNI / NIF/ Pasaporte");

        jLabel3.setText("E-Mail");

        jLabel4.setText("Domicilio");

        Localidad.setText("Localidad");

        jLabel6.setText("Código Postal");

        jLabel7.setText("Teléfono");

        jLabel9.setText("Apellidos");

        jLabel10.setText("Fecha Nacimiento");

        jLabel11.setText("Sexo");

        jLabel12.setText("Provincia");

        jLabel13.setText("Movil");

        btHacerSocio.setText("Hacer Socio");

        javax.swing.GroupLayout PanelDatosColaboradorLayout = new javax.swing.GroupLayout(PanelDatosColaborador);
        PanelDatosColaborador.setLayout(PanelDatosColaboradorLayout);
        PanelDatosColaboradorLayout.setHorizontalGroup(
            PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btHacerSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosColaboradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGuardarDatosColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btLimpiarDatosColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(63, 63, 63)))
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCP, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(575, 575, 575))
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7)
                            .addComponent(label17))
                        .addContainerGap())
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(Localidad))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosColaboradorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                .addGap(482, 482, 482)
                                .addComponent(label14))
                            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                                        .addComponent(radioSexoMasculinoSocio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioSexoFemeninoSocio))
                                    .addComponent(jFormattedTextFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextApellidos)
                                    .addComponent(jTextProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                    .addComponent(jTextMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))))
        );
        PanelDatosColaboradorLayout.setVerticalGroup(
            PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addComponent(label7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(label14))
                    .addGroup(PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(radioSexoMasculinoSocio)
                            .addComponent(radioSexoFemeninoSocio))))
                .addGap(38, 38, 38)
                .addComponent(label17)
                .addGap(33, 33, 33)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Localidad)
                        .addComponent(jTextLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jTextMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, Short.MAX_VALUE)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError)
                    .addComponent(btHacerSocio))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpiarDatosColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardarDatosColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPaneColaboradores.addTab("Datos", PanelDatosColaborador);

        PanelColaboracionesColaborador.setBackground(new java.awt.Color(255, 255, 255));

        label43.setForeground(new java.awt.Color(255, 0, 0));
        label43.setText("Colaboraciones");

        JtableColaboracionesColaborador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Fecha", "Concepto", "Confirmada por"
            }
        ));
        jScrollPane13.setViewportView(JtableColaboracionesColaborador);

        label44.setForeground(new java.awt.Color(255, 0, 0));
        label44.setText("Añadir colaboracion");

        label45.setText("Cantidad");

        label46.setText("Concepto");

        JtextConceptoColaborador.setText("Concepto dado en el ingreso, si lo hay");

        label47.setText("Fecha");

        btGuardarColaboracionColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/guardar.png"))); // NOI18N

        btBuscarColaboraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/buscar.png"))); // NOI18N

        btEliminarColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/borrar.png"))); // NOI18N

        jFormattedTextFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jFormattedTextFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jFormattedTextFechaFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel5.setText("Fecha inicial");

        jLabel8.setText("Fecha final");

        labelErrorColaboracion.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelErrorColaboracion.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorColaboracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErrorColaboracion.setText("Error");

        javax.swing.GroupLayout PanelColaboracionesColaboradorLayout = new javax.swing.GroupLayout(PanelColaboracionesColaborador);
        PanelColaboracionesColaborador.setLayout(PanelColaboracionesColaboradorLayout);
        PanelColaboracionesColaboradorLayout.setHorizontalGroup(
            PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)))
                                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(btBuscarColaboraciones)
                                        .addGap(18, 18, 18)
                                        .addComponent(btEliminarColaborador)))
                                .addContainerGap())))
                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label44)
                            .addComponent(label43)
                            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label45)
                                    .addComponent(label46))
                                .addGap(29, 29, 29)
                                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtextConceptoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                        .addComponent(JtextCantidadColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(label47)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(60, 60, 60)
                        .addComponent(btGuardarColaboracionColaborador)
                        .addGap(58, 142, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColaboracionesColaboradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelErrorColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        PanelColaboracionesColaboradorLayout.setVerticalGroup(
            PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                .addComponent(btBuscarColaboraciones)
                                .addGap(103, 103, 103)
                                .addComponent(btGuardarColaboracionColaborador))
                            .addComponent(btEliminarColaborador)))
                    .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelColaboracionesColaboradorLayout.createSequentialGroup()
                                .addComponent(label44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label45)
                                    .addComponent(JtextCantidadColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label47)
                                .addComponent(jFormattedTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(PanelColaboracionesColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label46)
                            .addComponent(JtextConceptoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(labelErrorColaboracion)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPaneColaboradores.addTab("Colaboraciones", PanelColaboracionesColaborador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPaneColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPaneColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableColaboracionesColaborador;
    private javax.swing.JTextField JtextCantidadColaborador;
    private javax.swing.JTextField JtextConceptoColaborador;
    private javax.swing.JLabel Localidad;
    private javax.swing.JPanel PanelColaboracionesColaborador;
    private javax.swing.JPanel PanelDatosColaborador;
    private javax.swing.JButton btBuscarColaboraciones;
    private javax.swing.JButton btEliminarColaborador;
    private javax.swing.JButton btGuardarColaboracionColaborador;
    private javax.swing.JButton btGuardarDatosColaborador;
    private javax.swing.JButton btHacerSocio;
    private javax.swing.JButton btLimpiarDatosColaborador;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JFormattedTextField jFormattedTextFecha;
    private javax.swing.JFormattedTextField jFormattedTextFechaFinal;
    private javax.swing.JFormattedTextField jFormattedTextFechaInicio;
    private javax.swing.JFormattedTextField jFormattedTextFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTabbedPane jTabbedPaneColaboradores;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCP;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDomicilio;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextLocalidad;
    private javax.swing.JTextField jTextMovil;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextProvincia;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label43;
    private javax.swing.JLabel label44;
    private javax.swing.JLabel label45;
    private javax.swing.JLabel label46;
    private javax.swing.JLabel label47;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelErrorColaboracion;
    private javax.swing.JRadioButton radioSexoFemeninoSocio;
    private javax.swing.JRadioButton radioSexoMasculinoSocio;
    // End of variables declaration//GEN-END:variables
}
