/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Colaborador;

import Vistas.Paneles.Colaborador.*;
import Vistas.BarraDeNavegacion;
import java.awt.CardLayout;

/**
 *
 * @author raphaelcolleau
 */
public class VistaColaborador extends javax.swing.JPanel {

    /* identificador de los paneles en el CardLayout */
    public static String panelInicio = "inicio";
    public static String panelBuscar = "buscar";
    public static String panelDatos = "datos";



    /**
     * Creates new form PanelVoluntario
     */
    public VistaColaborador() {
        initComponents();
    }

    // getter panel
    public BarraDeNavegacion getBarraDeNavegacion() {
        //System.out.println("Barra de navegacion Vista socio");
        return barraDeNavegacion;
    }

    public PanelColaboradorInicio getPanelColaboradorInicio() {
        return panelColaboradorInicio;
    }

    public PanelColaboradorDatos getPanelColaboradorDatos() {
        return panelColaboradorDatos;
    }

    public PanelColaboradorBuscar getPanelColaboradorBuscar() {
        return panelColaboradorBuscar;
    }

    // mostrar un panel con el CardLayoud
    public void showPanel (String panel) {
        CardLayout cardLayout =  (CardLayout)panelColaborador.getLayout();
        cardLayout.show(panelColaborador, panel);
        System.out.println("ShowPanel vista Socio"); 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeNavegacion = new Vistas.BarraDeNavegacion();
        panelColaborador = new javax.swing.JPanel();
        panelColaboradorInicio = new Vistas.Paneles.Colaborador.PanelColaboradorInicio();
        panelColaboradorDatos = new Vistas.Paneles.Colaborador.PanelColaboradorDatos();
        panelColaboradorBuscar = new Vistas.Paneles.Colaborador.PanelColaboradorBuscar();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        barraDeNavegacion.setAlignmentX(10.0F);

        panelColaborador.setMaximumSize(new java.awt.Dimension(1000, 550));
        panelColaborador.setMinimumSize(new java.awt.Dimension(1000, 550));
        panelColaborador.setPreferredSize(new java.awt.Dimension(1000, 550));
        panelColaborador.setLayout(new java.awt.CardLayout());

        panelColaboradorInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelColaborador.add(panelColaboradorInicio, "inicio");

        panelColaboradorDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelColaborador.add(panelColaboradorDatos, "datos");
        panelColaborador.add(panelColaboradorBuscar, "buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDeNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraDeNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.BarraDeNavegacion barraDeNavegacion;
    private javax.swing.JPanel panelColaborador;
    private Vistas.Paneles.Colaborador.PanelColaboradorBuscar panelColaboradorBuscar;
    private Vistas.Paneles.Colaborador.PanelColaboradorDatos panelColaboradorDatos;
    private Vistas.Paneles.Colaborador.PanelColaboradorInicio panelColaboradorInicio;
    // End of variables declaration//GEN-END:variables

}
