/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Beneficiario;

import java.awt.event.ActionListener;

/**
 *
 * @author psylock
 */
public class PanelBeneficiarioInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelBeneficiarioInicio
     */
    public PanelBeneficiarioInicio() {
        initComponents();
    }

    // LISTENERS

    public void anadirListenerbtBuscarBeneficiario(ActionListener listener){
        this.btBuscarBeneficiario.addActionListener(listener);
    }
    
    public void anadirListenerbtNuevoBeneficiario(ActionListener listener){
        this.btNuevoBeneficiario.addActionListener(listener);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNuevoBeneficiario = new javax.swing.JButton();
        btBuscarBeneficiario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        btNuevoBeneficiario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btNuevoBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/usu.png"))); // NOI18N
        btNuevoBeneficiario.setText("NUEVO BENEFICIARIO");
        btNuevoBeneficiario.setActionCommand("nuevoBeneficiario");
        btNuevoBeneficiario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNuevoBeneficiario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btBuscarBeneficiario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBuscarBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa (1).png"))); // NOI18N
        btBuscarBeneficiario.setText("BUSCAR");
        btBuscarBeneficiario.setActionCommand("buscarBeneficiario");
        btBuscarBeneficiario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscarBeneficiario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(217, 217, 217)
                .add(btNuevoBeneficiario)
                .add(116, 116, 116)
                .add(btBuscarBeneficiario)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {btBuscarBeneficiario, btNuevoBeneficiario}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(183, 183, 183)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btBuscarBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btNuevoBeneficiario))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {btBuscarBeneficiario, btNuevoBeneficiario}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarBeneficiario;
    private javax.swing.JButton btNuevoBeneficiario;
    // End of variables declaration//GEN-END:variables
}
