/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Beneficiario;

import Vistas.BarraDeNavegacion;
import Vistas.Paneles.Beneficiario.PanelBeneficiarioBuscar;
import Vistas.Paneles.Beneficiario.PanelBeneficiarioDatos;
import java.awt.CardLayout;

/**
 *
 * @author psylock
 */
public class VistaBeneficiario extends javax.swing.JPanel {

     /* identificador de los paneles en el CardLayout */ 
    public static String panelInicio = "inicio";
    public static String panelBuscar = "buscar";
    public static String panelDatos = "datos";

    
    /**
     * Creates new form VistaBeneficiario
     */
    public VistaBeneficiario() {
        initComponents();
    }

    
     // mostrar un panel con el CardLayoud
    public void showPanel (String panel) {
        CardLayout cardLayout =  (CardLayout)panelBeneficiario.getLayout();
        cardLayout.show(panelBeneficiario, panel);
    }
    
    
    public BarraDeNavegacion getBarraDeNavigacion() {
       return this.barraDeNavegacion;
    }
    
    
    public PanelBeneficiarioDatos getPanelDatos(){
        return this.panelBeneficiarioDatos;
    }
    
    public PanelBeneficiarioBuscar getPanelBuscar(){
        return this.panelBeneficiarioBuscar;
    }
    
    public PanelBeneficiarioInicio getPanelInicio(){
        return this.panelBeneficiarioInicio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeNavegacion = new Vistas.BarraDeNavegacion();
        panelBeneficiario = new javax.swing.JPanel();
        panelBeneficiarioBuscar = new Vistas.Paneles.Beneficiario.PanelBeneficiarioBuscar();
        panelBeneficiarioDatos = new Vistas.Paneles.Beneficiario.PanelBeneficiarioDatos();
        panelBeneficiarioInicio = new Vistas.Paneles.Beneficiario.PanelBeneficiarioInicio();

        setLayout(new java.awt.BorderLayout());
        add(barraDeNavegacion, java.awt.BorderLayout.PAGE_START);

        panelBeneficiario.setLayout(new java.awt.CardLayout());
        panelBeneficiario.add(panelBeneficiarioBuscar, "buscar");
        panelBeneficiario.add(panelBeneficiarioDatos, "datos");
        panelBeneficiario.add(panelBeneficiarioInicio, "inicio");

        add(panelBeneficiario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.BarraDeNavegacion barraDeNavegacion;
    private javax.swing.JPanel panelBeneficiario;
    private Vistas.Paneles.Beneficiario.PanelBeneficiarioBuscar panelBeneficiarioBuscar;
    private Vistas.Paneles.Beneficiario.PanelBeneficiarioDatos panelBeneficiarioDatos;
    private Vistas.Paneles.Beneficiario.PanelBeneficiarioInicio panelBeneficiarioInicio;
    // End of variables declaration//GEN-END:variables
}
