/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 ** DESCRIPCION :
 *      Barra de navigacion generica
 * 
 * @author raphaelcolleau
 */
public class BarraDeNavegacion extends javax.swing.JPanel {
    
    ActionListener listener;
    /**
     * Creates new form BarraDeNavegacion
     */
    public BarraDeNavegacion() {
        initComponents();
        senalaPrincipal.setVisible(false);
        labelMenuPrincipal.setVisible(false);
        senalaAvanzado.setVisible(false);
        labelMenuAvanzado.setVisible(false);
    }

    // anadir el listener de un controlador para recibir los eventos
    public void setListener(ActionListener listener) {
        this.listener = listener;
    }
    
    // indicar un texto de la vista
    public void setTextLabelMenuPrincipal (String text) {
        labelMenuPrincipal.setText(text);
        labelMenuPrincipal.setVisible(true);
        senalaPrincipal.setVisible(true);
    }
    
    // indicar un texto del panel
    public void setTextLabelMenuAvanzado (String text) {
        labelMenuAvanzado.setText(text);
        labelMenuAvanzado.setVisible(true);
        senalaAvanzado.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navToMain = new javax.swing.JButton();
        senalaPrincipal = new javax.swing.JLabel();
        labelMenuPrincipal = new javax.swing.JLabel();
        senalaAvanzado = new javax.swing.JLabel();
        labelMenuAvanzado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 50));
        setMinimumSize(new java.awt.Dimension(1000, 50));
        setPreferredSize(new java.awt.Dimension(1000, 50));

        navToMain.setForeground(new java.awt.Color(0, 0, 255));
        navToMain.setText("DIAKETAS");
        navToMain.setActionCommand("navToMainFromVoluntarios");
        navToMain.setBorderPainted(false);
        navToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navToMainActionPerformed(evt);
            }
        });

        senalaPrincipal.setForeground(new java.awt.Color(153, 153, 153));
        senalaPrincipal.setText(">");

        labelMenuPrincipal.setText("Voluntario");
        labelMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMenuPrincipalMouseClicked(evt);
            }
        });

        senalaAvanzado.setForeground(new java.awt.Color(153, 153, 153));
        senalaAvanzado.setText(">");

        labelMenuAvanzado.setText("Buscar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(layout.createSequentialGroup()
                        .add(navToMain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaPrincipal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(labelMenuPrincipal)
                        .add(32, 32, 32)
                        .add(senalaAvanzado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(labelMenuAvanzado)
                        .add(0, 660, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(navToMain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(senalaPrincipal)
                    .add(labelMenuPrincipal)
                    .add(senalaAvanzado)
                    .add(labelMenuAvanzado))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void navToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navToMainActionPerformed
        senalaPrincipal.setVisible(false);
        labelMenuPrincipal.setVisible(false);
        senalaAvanzado.setVisible(false);
        labelMenuAvanzado.setVisible(false);
        
        // manda un event al controlador para cambiar de panel
        ActionEvent event = new ActionEvent(this, 0, "toMain");
        listener.actionPerformed(event);
    }//GEN-LAST:event_navToMainActionPerformed

    private void labelMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuPrincipalMouseClicked

        senalaAvanzado.setVisible(false);
        labelMenuAvanzado.setVisible(false);
        
        // manda un event al controlador para cambiar de panel
        ActionEvent event = new ActionEvent(this, 0, "toMenuInicial");
        listener.actionPerformed(event);
    }//GEN-LAST:event_labelMenuPrincipalMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMenuAvanzado;
    private javax.swing.JLabel labelMenuPrincipal;
    private javax.swing.JButton navToMain;
    private javax.swing.JLabel senalaAvanzado;
    private javax.swing.JLabel senalaPrincipal;
    // End of variables declaration//GEN-END:variables
}
