package Vistas;

import java.awt.event.ActionListener;

/**
*
* @author psylock
*/
public class VistaInicial extends javax.swing.JPanel {

    /**
* Creates new form VistaInicial
*/
    public VistaInicial() {
        initComponents();
    }

     /** LISTENERS */

    public void anadirListenerbtBeneficiario(ActionListener listener){
        this.btBeneficiario.addActionListener(listener);
    }

    public void anadirListenerbtBolsaTrabajo(ActionListener listener){
        this.btBolsaTrabajo.addActionListener(listener);
    }

    public void anadirListenerbtSocio(ActionListener listener){
        this.btColaboradores.addActionListener(listener);
    }

    public void anadirListenerbtVoluntario(ActionListener listener) {
        this.btVoluntario.addActionListener(listener);
    }

    public void anadirListenerbtDesconectase(ActionListener listener) {
        this.btDesconectarse.addActionListener(listener);
    }

    public void anadirListenerbtColaboradores(ActionListener listener){
        this.btColaboradores.addActionListener(listener);
    }

    /**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btColaboradores = new javax.swing.JButton();
        btBeneficiario = new javax.swing.JButton();
        btVoluntario = new javax.swing.JButton();
        btBolsaTrabajo = new javax.swing.JButton();
        btDesconectarse = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));

        btColaboradores.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btColaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/socio.png"))); // NOI18N
        btColaboradores.setText("COLABORADORES");
        btColaboradores.setToolTipText("Acceso a Colaboradores");
        btColaboradores.setActionCommand("entrarAPanelSocios");
        btColaboradores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btColaboradores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColaboradores.setMaximumSize(new java.awt.Dimension(161, 159));
        btColaboradores.setMinimumSize(new java.awt.Dimension(161, 159));
        btColaboradores.setName("");
        btColaboradores.setPreferredSize(new java.awt.Dimension(161, 159));
        btColaboradores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColaboradoresActionPerformed(evt);
            }
        });

        btBeneficiario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/bene.png"))); // NOI18N
        btBeneficiario.setText("BENEFICIARIOS");
        btBeneficiario.setToolTipText("Acceso a Beneficiarios");
        btBeneficiario.setActionCommand("entrarAPanelBeneficiarios");
        btBeneficiario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBeneficiario.setPreferredSize(new java.awt.Dimension(161, 159));
        btBeneficiario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btVoluntario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgVolunt.jpg"))); // NOI18N
        btVoluntario.setText("VOLUNTARIOS");
        btVoluntario.setToolTipText("Acceso a Voluntarios");
        btVoluntario.setActionCommand("entrarAPanelVoluntarios");
        btVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoluntario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btBolsaTrabajo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBolsaTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgBolsa.jpg"))); // NOI18N
        btBolsaTrabajo.setText("BOLSA DE TRABAJO");
        btBolsaTrabajo.setActionCommand("entrarAPanelBolsaTrabajo");
        btBolsaTrabajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBolsaTrabajo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btDesconectarse.setText("Desconectarse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btDesconectarse)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(btBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(btBolsaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btDesconectarse)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBolsaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColaboradoresActionPerformed

    }//GEN-LAST:event_btColaboradoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeneficiario;
    private javax.swing.JButton btBolsaTrabajo;
    private javax.swing.JButton btColaboradores;
    private javax.swing.JButton btDesconectarse;
    private javax.swing.JButton btVoluntario;
    // End of variables declaration//GEN-END:variables
}