/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.ModeloBeneficiarioBuscar;
import Modelos.ModeloVistaLogin;
import java.awt.event.ActionListener;

/**
 *
 * @author psylock
 */
public class VistaBeneficiarioBuscar extends javax.swing.JPanel {

    private static ModeloBeneficiarioBuscar modelo;
    
    
    /**
     * Creates new form VistaBeneficiarioBuscar
     */
    public VistaBeneficiarioBuscar() {
        initComponents();
        VistaBeneficiarioBuscar.modelo = new ModeloBeneficiarioBuscar();
    }
    
    public ModeloBeneficiarioBuscar getModelo(){
        return VistaBeneficiarioBuscar.modelo;
    }
    
    public void setModelo(ModeloBeneficiarioBuscar model){
        VistaBeneficiarioBuscar.modelo = model;
    }
    
    
    public void actualizarModelo(){
        VistaBeneficiarioBuscar.modelo.setDNIBeneficiario(this.textBusquedaBeneficiarioDNI.getText());
        VistaBeneficiarioBuscar.modelo.setCriterio(this.cbTipoBusquedaBeneficiario.getSelectedIndex());
    }
    
    /** LISTENERS **/
    
    public void anadirListenerbtBuscarBeneficiarioDNI(ActionListener listener){
        this.btBuscarBeneficiarioDNI.addActionListener(listener);
    }
    
    public void anadirListenerbtVerBeneficiarioBusqueda(ActionListener listener){
        this.btVerBeneficiarioBusqueda.addActionListener(listener);
    }
    
    public void anadirListenernavToBeneficiariosFromBuscarBeneficiario(ActionListener listener){
        this.navToBeneficiariosFromBuscarBeneficiario.addActionListener(listener);
    }
    
    public void anadirListenernavToMainFromBuscarBeneficiario(ActionListener listener){
        this.navToMainFromBuscarBeneficiario.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorBeneficiario1 = new javax.swing.JSeparator();
        senalaBeneficiario1 = new javax.swing.JLabel();
        navToMainFromBuscarBeneficiario = new javax.swing.JButton();
        navToBeneficiariosFromBuscarBeneficiario = new javax.swing.JButton();
        senalaBeneficiario2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textBusquedaBeneficiarioDNI = new javax.swing.JTextField();
        btBuscarBeneficiarioDNI = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        cbTipoBusquedaBeneficiario = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaBusquedaBeneficiario = new javax.swing.JTable();
        btVerBeneficiarioBusqueda = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        senalaBeneficiario1.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario1.setText(">");

        navToMainFromBuscarBeneficiario.setForeground(new java.awt.Color(0, 0, 255));
        navToMainFromBuscarBeneficiario.setText("DIAKETAS");
        navToMainFromBuscarBeneficiario.setActionCommand("navToMainFromBuscarBeneficiario");
        navToMainFromBuscarBeneficiario.setBorderPainted(false);

        navToBeneficiariosFromBuscarBeneficiario.setForeground(new java.awt.Color(0, 0, 255));
        navToBeneficiariosFromBuscarBeneficiario.setText("Beneficiarios");
        navToBeneficiariosFromBuscarBeneficiario.setActionCommand("navToBeneficiariosFromBuscarBeneficiario");
        navToBeneficiariosFromBuscarBeneficiario.setBorderPainted(false);

        senalaBeneficiario2.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario2.setText(">");

        jLabel27.setText("Buscar Beneficiario");

        btBuscarBeneficiarioDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/buscar.png"))); // NOI18N
        btBuscarBeneficiarioDNI.setActionCommand("buscarBeneficiarioDNI");

        jLabel29.setText("Criterio de búsqueda");

        cbTipoBusquedaBeneficiario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tablaBusquedaBeneficiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo Búsqueda", "DNI", "Nombre y Apellidos", "Fecha Nacimiento"
            }
        ));
        jScrollPane5.setViewportView(tablaBusquedaBeneficiario);

        btVerBeneficiarioBusqueda.setText("Ver beneficiario");
        btVerBeneficiarioBusqueda.setActionCommand("verBeneficiarioBusqueda");

        jLabel63.setText("Introduzca el DNI para buscar al beneficiario");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(separadorBeneficiario1)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(20, 20, 20)
                                        .add(jLabel63)
                                        .add(18, 18, 18)
                                        .add(textBusquedaBeneficiarioDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(btBuscarBeneficiarioDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(navToMainFromBuscarBeneficiario)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(senalaBeneficiario1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(navToBeneficiariosFromBuscarBeneficiario)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(senalaBeneficiario2)
                                        .add(26, 26, 26)
                                        .add(jLabel27)))
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 20, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel29)
                                .add(18, 18, 18)
                                .add(cbTipoBusquedaBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(btVerBeneficiarioBusqueda)
                                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 948, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(senalaBeneficiario1)
                    .add(navToMainFromBuscarBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(navToBeneficiariosFromBuscarBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(senalaBeneficiario2)
                    .add(jLabel27))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(separadorBeneficiario1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel63)
                            .add(textBusquedaBeneficiarioDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btBuscarBeneficiarioDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel29)
                    .add(cbTipoBusquedaBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btVerBeneficiarioBusqueda)
                .add(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarBeneficiarioDNI;
    private javax.swing.JButton btVerBeneficiarioBusqueda;
    private javax.swing.JComboBox cbTipoBusquedaBeneficiario;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton navToBeneficiariosFromBuscarBeneficiario;
    private javax.swing.JButton navToMainFromBuscarBeneficiario;
    private javax.swing.JLabel senalaBeneficiario1;
    private javax.swing.JLabel senalaBeneficiario2;
    private javax.swing.JSeparator separadorBeneficiario1;
    private javax.swing.JTable tablaBusquedaBeneficiario;
    private javax.swing.JTextField textBusquedaBeneficiarioDNI;
    // End of variables declaration//GEN-END:variables
}
