/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.ModeloVistaLogin;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author psylock
 */
public class VistaLogin extends javax.swing.JPanel {

    private static ModeloVistaLogin modelo;
    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        VistaLogin.modelo = new ModeloVistaLogin();
        this.textErrorLogin.setVisible(false);
    }

    public JButton getBtConectarse() {
        return btConectarse;
    }

    public JLabel getTextErrorLogin() {
        return textErrorLogin;
    }

    public JPasswordField getTextFieldContrasena() {
        return textFieldContrasena;
    }

    public JTextField getTextFieldIdUsuario() {
        return textFieldIdUsuario;
    }
    
    public ModeloVistaLogin getModelo(){
        return VistaLogin.modelo;
    }
    
    public void setModelo(ModeloVistaLogin model){
        VistaLogin.modelo = model;
    }
    
    public void actualizarModelo(){
        VistaLogin.modelo.setUsuario(this.textFieldIdUsuario.getText());
        VistaLogin.modelo.setPass(new String(this.textFieldContrasena.getPassword()));
    }
    
    /** LISTENERS */
    
    public void anadirListenerBtConectarse(ActionListener listener){
        this.btConectarse.addActionListener(listener);
    }
    
    /** FUNCIONES VARIAS */
    
    public void mostrarErrorLogin(String cadena){
        this.textErrorLogin.setText(cadena);
        this.textErrorLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imgLogo = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textFieldIdUsuario = new javax.swing.JTextField();
        btConectarse = new javax.swing.JButton();
        textFieldContrasena = new javax.swing.JPasswordField();
        textErrorLogin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/Acceso_Usuarios.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(148, 74, 0, 0);
        add(imgLogo, gridBagConstraints);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setText("BIENVENIDO A DIAKETAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(148, 98, 0, 201);
        add(labelTitulo, gridBagConstraints);

        labelUsuario.setText("USUARIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(141, 61, 0, 0);
        add(labelUsuario, gridBagConstraints);

        labelContrasena.setText("CONTRASEÑA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 30, 0, 0);
        add(labelContrasena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 208;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(135, 94, 0, 201);
        add(textFieldIdUsuario, gridBagConstraints);

        btConectarse.setText("Entrar");
        btConectarse.setActionCommand("accionLogin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 182, 0, 201);
        add(btConectarse, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 208;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 94, 0, 201);
        add(textFieldContrasena, gridBagConstraints);

        textErrorLogin.setForeground(new java.awt.Color(255, 0, 0));
        textErrorLogin.setText("ERROR AL HACER LOGIN. INTÉNTELO DE NUEVO.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 98, 86, 0);
        add(textErrorLogin, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectarse;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel textErrorLogin;
    private javax.swing.JPasswordField textFieldContrasena;
    private javax.swing.JTextField textFieldIdUsuario;
    // End of variables declaration//GEN-END:variables
}
