/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Voluntario;

import java.awt.event.ActionListener;

/**
 *
 * @author psylock
 */
public class PanelVoluntarioInicio extends javax.swing.JPanel {

    /**
     * Creates new form VistaPanelVoluntarioInicio
     */
    public PanelVoluntarioInicio() {
        initComponents();
    }

     /** LISTENERS */
    
    public void anadirListenerbtAyudas(ActionListener listener){
        this.btAyudas.addActionListener(listener);
    }
    
    public void anadirListenerbtBuscarVoluntario(ActionListener listener){
        this.btBuscarVoluntario.addActionListener(listener);
    }
      
    public void anadirListenerbtColaboraciones(ActionListener listener){
        this.btColaboraciones.addActionListener(listener);
    }
        
    public void anadirListenerbtContabilidad(ActionListener listener){
        this.btContabilidad.addActionListener(listener);
    }
    
     
    public void anadirListenerbtNuevoVoluntario(ActionListener listener){
        this.btNuevoVoluntario.addActionListener(listener);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNuevoVoluntario = new javax.swing.JButton();
        btBuscarVoluntario = new javax.swing.JButton();
        btContabilidad = new javax.swing.JButton();
        btAyudas = new javax.swing.JButton();
        btColaboraciones = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        btNuevoVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/vol.png"))); // NOI18N
        btNuevoVoluntario.setActionCommand("nuevoVoluntario");

        btBuscarVoluntario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBuscarVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa.png"))); // NOI18N
        btBuscarVoluntario.setText("BUSCAR");
        btBuscarVoluntario.setActionCommand("buscarVoluntario");
        btBuscarVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscarVoluntario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btContabilidad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/contabilidad.jpg"))); // NOI18N
        btContabilidad.setText("Contabilidad");
        btContabilidad.setActionCommand("contabilidad");
        btContabilidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btContabilidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btAyudas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btAyudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/images.jpg"))); // NOI18N
        btAyudas.setText("AYUDAS");
        btAyudas.setActionCommand("ayudas");
        btAyudas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAyudas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btColaboraciones.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btColaboraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/monigote-devoluciones_1.jpg"))); // NOI18N
        btColaboraciones.setText("Colaboraciones");
        btColaboraciones.setActionCommand("contabilidad");
        btColaboraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColaboraciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNuevoVoluntario)
                        .addGap(243, 243, 243)
                        .addComponent(btBuscarVoluntario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(btColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(btAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNuevoVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarVoluntario))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAyudas;
    private javax.swing.JButton btBuscarVoluntario;
    private javax.swing.JButton btColaboraciones;
    private javax.swing.JButton btContabilidad;
    private javax.swing.JButton btNuevoVoluntario;
    // End of variables declaration//GEN-END:variables
}
