/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Voluntario;

import javax.swing.*;

/**
 *
 * @author raphaelcolleau
 */
public class PanelVoluntarioAyudas extends javax.swing.JPanel {

    /**
     * Creates new form PanelVoluntarioAyudas
     */
    public PanelVoluntarioAyudas() {
        initComponents();
        labelErrorAyuda.setVisible(false);
        labelErrorTipoAyuda.setVisible(false);
    }
    
    public void setTextErrorTipoAyuda (String text) {
        labelErrorTipoAyuda.setText(text);
        labelErrorTipoAyuda.setVisible(true);
    }

    public JLabel getLabelErrorTipoAyuda() {
        return labelErrorTipoAyuda;
    }
    
    public void setTextErrorAyuda (String text) {
        labelErrorAyuda.setText(text);
        labelErrorAyuda.setVisible(true);
    }

    public JLabel getLabelErrorAyuda() {
        return labelErrorAyuda;
    }

    public JButton getBtnBuscarAyudas() {
        return btnBuscarAyudas;
    }

    public JButton getBtnEliminarTipoAyuda() {
        return btnEliminarTipoAyuda;
    }

    public JButton getBtnGuardarTipoAyuda() {
        return btnGuardarTipoAyuda;
    }

    public JComboBox getCbTipoAyuda() {
        return cbTipoAyuda;
    }

    public JTextField getTextTipoAyuda() {
        return textTipoAyuda;
    }

    public JTextField getDescripcionTipoAyuda() {
        return descripcionTipoAyuda;
    }

    public JTextField getFechaFinAyudas() {
        return fechaFinAyudas;
    }

    public JTextField getFechaInicioAyudas() {
        return fechaInicioAyudas;
    }

    public JCheckBox getIsMonetaria() {
        return isMonetaria;
    }

    public JTextField getMaximoImporte() {
        return maximoImporte;
    }

    public JTextField getMinimoImporte() {
        return minimoImporte;
    }

    public JTable getTablaAyudas() {
        return tablaAyudas;
    }

    public JTable getTablaTiposAyuda() {
        return tablaTiposAyuda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAyudas = new javax.swing.JTable();
        btnBuscarAyudas = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textTipoAyuda = new javax.swing.JTextField();
        btnEliminarTipoAyuda = new javax.swing.JButton();
        btnGuardarTipoAyuda = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTiposAyuda = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        cbTipoAyuda = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        fechaInicioAyudas = new javax.swing.JTextField();
        fechaFinAyudas = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        minimoImporte = new javax.swing.JTextField();
        maximoImporte = new javax.swing.JTextField();
        descripcionTipoAyuda = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        isMonetaria = new javax.swing.JCheckBox();
        labelErrorAyuda = new javax.swing.JLabel();
        labelErrorTipoAyuda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Listado de ayudas");

        tablaAyudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Concepto", "DNI"
            }
        ));
        jScrollPane3.setViewportView(tablaAyudas);

        btnBuscarAyudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/buscar.png"))); // NOI18N
        btnBuscarAyudas.setActionCommand("buscarBeneficiarioAyuda");

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Gestión tipos de ayudas");

        jLabel26.setText("Nombre de un tipo");

        btnEliminarTipoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/borrar.png"))); // NOI18N
        btnEliminarTipoAyuda.setActionCommand("eliminarTipoAyuda");

        btnGuardarTipoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/guardar.png"))); // NOI18N
        btnGuardarTipoAyuda.setActionCommand("guardarTipoAyuda");

        tablaTiposAyuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Descripcion", "Monetaria"
            }
        ));
        jScrollPane4.setViewportView(tablaTiposAyuda);

        jLabel27.setText("Tipo de ayuda");

        cbTipoAyuda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel28.setText("Fecha de la ayuda");

        fechaInicioAyudas.setText("Inicio");

        fechaFinAyudas.setText("Fin");

        jLabel29.setText("Importe");

        minimoImporte.setText("Minimo");

        maximoImporte.setText("Maximo");

        jLabel30.setText("Descripción");

        jLabel31.setText("Monetaria");

        labelErrorAyuda.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorAyuda.setText("label error");

        labelErrorTipoAyuda.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorTipoAyuda.setText("label error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fechaInicioAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(minimoImporte))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fechaFinAyudas)
                                            .addComponent(maximoImporte, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel29))
                                    .addComponent(cbTipoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelErrorAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscarAyudas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(57, 57, 57)
                                .addComponent(textTipoAyuda)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelErrorTipoAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(btnGuardarTipoAyuda)
                        .addGap(41, 41, 41)
                        .addComponent(btnEliminarTipoAyuda)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isMonetaria)
                            .addComponent(descripcionTipoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel25))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(textTipoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(descripcionTipoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel31)
                                    .addComponent(isMonetaria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbTipoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelErrorTipoAyuda)
                                        .addGap(25, 25, 25))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardarTipoAyuda)
                                    .addComponent(btnEliminarTipoAyuda))
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fechaInicioAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaFinAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(minimoImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maximoImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(btnBuscarAyudas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(labelErrorAyuda)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAyudas;
    private javax.swing.JButton btnEliminarTipoAyuda;
    private javax.swing.JButton btnGuardarTipoAyuda;
    private javax.swing.JComboBox cbTipoAyuda;
    private javax.swing.JTextField descripcionTipoAyuda;
    private javax.swing.JTextField fechaFinAyudas;
    private javax.swing.JTextField fechaInicioAyudas;
    private javax.swing.JCheckBox isMonetaria;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelErrorAyuda;
    private javax.swing.JLabel labelErrorTipoAyuda;
    private javax.swing.JTextField maximoImporte;
    private javax.swing.JTextField minimoImporte;
    private javax.swing.JTable tablaAyudas;
    private javax.swing.JTable tablaTiposAyuda;
    private javax.swing.JTextField textTipoAyuda;
    // End of variables declaration//GEN-END:variables
}
