/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Colaboradores;

import java.awt.event.ActionListener;

/**
 *
 * @author psylock
 */
public class PanelColaboradoresInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelBeneficiarioInicio
     */
    public PanelColaboradoresInicio() {
        initComponents();
    }

    // LISTENERS

    public void anadirListenerbtEmpresa(ActionListener listener){
        this.btEmpresa.addActionListener(listener);
    }
    
    public void anadirListenerbtSocio(ActionListener listener){
        this.btSocio.addActionListener(listener);
    }
    
    public void anadirListenerbtColaborador(ActionListener listener){
        this.btColaborador.addActionListener(listener);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btColaborador = new javax.swing.JButton();
        btSocio = new javax.swing.JButton();
        btEmpresa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        btColaborador.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/monigotes_redimensionados.png"))); // NOI18N
        btColaborador.setText("COLABORADORES");
        btColaborador.setActionCommand("nuevoBeneficiario");
        btColaborador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColaborador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btSocio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/socios.jpg"))); // NOI18N
        btSocio.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        btSocio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSocio.setLabel("SOCIO");
        btSocio.setMaximumSize(new java.awt.Dimension(215, 183));
        btSocio.setMinimumSize(new java.awt.Dimension(215, 183));
        btSocio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btEmpresa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/empresas-redimensionada.jpg"))); // NOI18N
        btEmpresa.setText("EMPRESA");
        btEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(95, 95, 95)
                .add(btColaborador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 402, Short.MAX_VALUE)
                .add(btSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(99, 99, 99))
            .add(layout.createSequentialGroup()
                .add(406, 406, 406)
                .add(btEmpresa)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(82, 82, 82)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btColaborador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(84, 84, 84)
                .add(btEmpresa)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btColaborador;
    private javax.swing.JButton btEmpresa;
    private javax.swing.JButton btSocio;
    // End of variables declaration//GEN-END:variables
}
