/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Colaboradores;

import java.awt.event.ActionListener;

/**
 *
 * @author psylock
 */
public class PanelColaboradoresInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelBeneficiarioInicio
     */
    public PanelColaboradoresInicio() {
        initComponents();
    }

    // LISTENERS

    public void anadirListenerbtEmpresa(ActionListener listener){
        this.btEmpresa.addActionListener(listener);
    }
    
    public void anadirListenerbtSocio(ActionListener listener){
        this.btSocio.addActionListener(listener);
    }
    
    public void anadirListenerbtColaborador(ActionListener listener){
        this.btColaborador.addActionListener(listener);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btColaborador = new javax.swing.JButton();
        btSocio = new javax.swing.JButton();
        btEmpresa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        btColaborador.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/monigotes_redimensionados.png"))); // NOI18N
        btColaborador.setText("COLABORADORES");
        btColaborador.setActionCommand("nuevoBeneficiario");
        btColaborador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColaborador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btSocio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/socios.jpg"))); // NOI18N
        btSocio.setText("SOCIO");
        btSocio.setActionCommand("buscarBeneficiario");
        btSocio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSocio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btEmpresa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/empresas-redimensionada.jpg"))); // NOI18N
        btEmpresa.setText("EMPRESA");
        btEmpresa.setActionCommand("nuevoBeneficiario");
        btEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(btColaborador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(709, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(364, Short.MAX_VALUE)
                            .add(btEmpresa)
                            .add(352, 352, 352))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(716, Short.MAX_VALUE)
                            .add(btSocio)))
                    .add(53, 53, 53)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(89, 89, 89)
                .add(btColaborador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(84, 84, 84)
                    .add(btSocio)
                    .add(70, 70, 70)
                    .add(btEmpresa)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btColaborador;
    private javax.swing.JButton btEmpresa;
    private javax.swing.JButton btSocio;
    // End of variables declaration//GEN-END:variables
}
