
package Vistas.Paneles.BolsaTrabajo;

import javax.swing.JButton;

public class PanelNuevaOferta extends javax.swing.JPanel {

	/**
		* Creates new form PanelBeneficiarioBuscar
		*/
	public PanelNuevaOferta() {
		initComponents();
	}

	/* Botones del panel */
	public JButton getBTEliminarSector(){
		return BTEliminarSector;
	}

	public JButton getBTGuardar(){
		return BTGuardar;
	}

	public JButton getBTGuardarSector(){
		return BTGuardarSector;
	}

	public JButton getBTLimpiar(){
        return BTLimpiar;
    }

	/* Campos del panel */
	public String getTextCIF(){
		return TextCIF.getText();
	}
	public void setTextCIF(String texto){
		TextCIF.setText(texto);
	}

	public String getcbSector(){
		return cbSector.getSelectedItem().toString();
	}

	public String getTextNuevoSector(){
		return TextNuevoSector.getText();
	}
	public void setTextNuevoSector(String texto){
		TextNuevoSector.setText(texto);
	}

	public String gettaDescripcionOferta(){
		return taDescripcionOferta.getText();
	}
	public void settaDescripcionOferta(String texto){
		taDescripcionOferta.setText(texto);
	}

	public String getTextNPuestos(){
		return TextNPuestos.getText();
	}
	public void setTextNPuestos(String texto){
		TextNPuestos.setText(texto);
	}

	public String getcbTipoContrato(){
		return cbTipoContrato.getSelectedItem().toString();
	}

	public String getTextDuracionContrato(){
		return TextDuracionContrato.getText();
	}
	public void setTextDuracionContrato(String texto){
		TextDuracionContrato.setText(texto);
	}

	public String gettaCualificacion(){
		return taCualificacion.getText();
	}
	public void settaCualificacion(String texto){
        taCualificacion.setText(texto);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTLimpiar = new javax.swing.JButton();
        BTGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelDescripcionOferta = new javax.swing.JLabel();
        labelNPuestos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcionOferta = new javax.swing.JTextArea();
        labelTipoContrato = new javax.swing.JLabel();
        labelDuracionContrato = new javax.swing.JLabel();
        TextNPuestos = new javax.swing.JTextField();
        cbTipoContrato = new javax.swing.JComboBox();
        labelMeses = new javax.swing.JLabel();
        TextDuracionContrato = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelCIF = new javax.swing.JLabel();
        labelSector = new javax.swing.JLabel();
        cbSector = new javax.swing.JComboBox();
        TextCIF = new javax.swing.JTextField();
        BTEliminarSector = new javax.swing.JButton();
        TextNuevoSector = new javax.swing.JTextField();
        BTGuardarSector = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCualificacion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        BTLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/limpiar.png"))); // NOI18N

        BTGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/guardar.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescripcionOferta.setText("Descripcion del puesto ofertado");

        labelNPuestos.setText("Nº de puestos");

        taDescripcionOferta.setColumns(20);
        taDescripcionOferta.setRows(5);
        taDescripcionOferta.setText("Descripción completa del puesto de trabajo");
        taDescripcionOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jScrollPane1.setViewportView(taDescripcionOferta);

        labelTipoContrato.setText("Tipo de contrato");

        labelDuracionContrato.setText("Duracion de contrato");

        TextNPuestos.setText("Numero");

        cbTipoContrato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fijo", "Temporal" }));

        labelMeses.setText("Meses");

        TextDuracionContrato.setText("12");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelDescripcionOferta)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(labelNPuestos)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(TextNPuestos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(53, 53, 53)
                                .add(labelTipoContrato)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(cbTipoContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(39, 39, 39)
                                .add(labelDuracionContrato)
                                .add(18, 18, 18)
                                .add(TextDuracionContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelMeses)))
                        .add(0, 333, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelDescripcionOferta)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelNPuestos)
                    .add(labelTipoContrato)
                    .add(labelDuracionContrato)
                    .add(TextNPuestos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbTipoContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelMeses)
                    .add(TextDuracionContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCIF.setText("CIF");

        labelSector.setText("Sector");

        cbSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economico" }));

        TextCIF.setText("CIF/ NIF");

        BTEliminarSector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/borrar.png"))); // NOI18N

        TextNuevoSector.setText("Nuevo Sector");

        BTGuardarSector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/guardar.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(labelCIF)
                .add(18, 18, 18)
                .add(TextCIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(76, 76, 76)
                .add(labelSector)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cbSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BTEliminarSector)
                .add(18, 18, 18)
                .add(TextNuevoSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BTGuardarSector)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(BTGuardarSector)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(21, 21, 21)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(TextCIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(labelCIF)
                                .add(cbSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(labelSector)))
                        .add(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(BTEliminarSector))
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(21, 21, 21)
                            .add(TextNuevoSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel68.setForeground(java.awt.Color.red);
        jLabel68.setText("Datos Empresa");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel69.setForeground(java.awt.Color.red);
        jLabel69.setText("Datos Oferta");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setForeground(java.awt.Color.red);
        jLabel71.setText("Cualificacion Requerida");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taCualificacion.setColumns(20);
        taCualificacion.setRows(5);
        taCualificacion.setText("Descripción completa de la cualificacion necesria");
        taCualificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jScrollPane2.setViewportView(taCualificacion);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(BTGuardar)
                        .add(18, 18, 18)
                        .add(BTLimpiar)
                        .add(389, 389, 389))
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel71))
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jLabel69))
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jLabel68)))
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel68)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel69)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel71)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(BTGuardar)
                    .add(BTLimpiar))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEliminarSector;
    private javax.swing.JButton BTGuardar;
    private javax.swing.JButton BTGuardarSector;
    private javax.swing.JButton BTLimpiar;
    private javax.swing.JTextField TextCIF;
    private javax.swing.JTextField TextDuracionContrato;
    private javax.swing.JTextField TextNPuestos;
    private javax.swing.JTextField TextNuevoSector;
    private javax.swing.JComboBox cbSector;
    private javax.swing.JComboBox cbTipoContrato;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCIF;
    private javax.swing.JLabel labelDescripcionOferta;
    private javax.swing.JLabel labelDuracionContrato;
    private javax.swing.JLabel labelMeses;
    private javax.swing.JLabel labelNPuestos;
    private javax.swing.JLabel labelSector;
    private javax.swing.JLabel labelTipoContrato;
    private javax.swing.JTextArea taCualificacion;
    private javax.swing.JTextArea taDescripcionOferta;
    // End of variables declaration//GEN-END:variables
}
