/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.BolsaTrabajo;

import Vistas.Paneles.Beneficiario.*;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JComboBox;
import javax.swing.JTextField;


/**
 *
 * @author psylock
 */
public class PanelDemandaBuscar extends javax.swing.JPanel {


    /**
     * Creates new form PanelBeneficiarioBuscar
     */
    public PanelDemandaBuscar() {
        initComponents();
    }

    public JButton getBTBuscar(){
        return BTBuscar3;
    }

    public JButton getBTEliminar(){
        return BTEliminar;
    }

    public JButton getBTModificar(){
        return BTEliminar;
    }

       public JComboBox getcbSector(){
        return cbSector;
   }

    public String getcbAntiguedad(){
        return cbAntiguedad.getSelectedItem().toString();
    }
    
    public String getTextoSector(){
        return cbSector.getSelectedItem().toString();
    }
    
    public JTable getTablaBusquedaDemandante(){
        return tablaBusquedaDemandante;
    }

    public String getTextBusquedaDemandanteDNI(){
        return textBusquedaDemandanteDNI.getText();
    }

    	public int getAntiguedad(){
		return cbAntiguedad.getSelectedIndex();
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tablaBusquedaDemandante = new javax.swing.JTable();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        textBusquedaDemandanteDNI = new javax.swing.JTextField();
        cbSector = new javax.swing.JComboBox();
        jLabel65 = new javax.swing.JLabel();
        cbAntiguedad = new javax.swing.JComboBox();
        BTEliminar = new javax.swing.JButton();
        BTModificar = new javax.swing.JButton();
        BTBuscar3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        tablaBusquedaDemandante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12345678E", "Pepe Morillas Bonico", "Construccion", null}
            },
            new String [] {
                "DNI", "Nombre y Apellidos", "Sector", "Fecha Demanda"
            }
        ));
        jScrollPane5.setViewportView(tablaBusquedaDemandante);

        jLabel63.setText("Demandante");

        jLabel64.setText("Sector Busqueda");

        textBusquedaDemandanteDNI.setText("DNI");

        cbSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Construccion", "Electricidad", "Carpinteria", "Fontaneria", " " }));

        jLabel65.setText("Antiguedad");

        cbAntiguedad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 mes", "2 meses", "3 meses", "4 meses", "5 meses", "6 meses", "7 meses", "8 meses", "9 meses", "10 meses", "11 meses", "12 meses", "mas de 1 año", " " }));

        BTEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/borrar.png"))); // NOI18N

        BTModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/modificar.png"))); // NOI18N

        BTBuscar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/buscar.png"))); // NOI18N
        BTBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuscar3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 948, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel63)
                        .add(18, 18, 18)
                        .add(textBusquedaDemandanteDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(69, 69, 69)
                        .add(jLabel64)
                        .add(18, 18, 18)
                        .add(cbSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(79, 79, 79)
                        .add(jLabel65)
                        .add(18, 18, 18)
                        .add(cbAntiguedad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(BTBuscar3)
                        .add(109, 109, 109))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(BTModificar)
                        .add(18, 18, 18)
                        .add(BTEliminar)
                        .add(389, 389, 389))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel63)
                        .add(jLabel64)
                        .add(textBusquedaDemandanteDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cbSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel65)
                        .add(cbAntiguedad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(BTBuscar3))
                .add(18, 18, 18)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .add(87, 87, 87)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(BTEliminar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(BTModificar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTBuscar3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBuscar3;
    private javax.swing.JButton BTEliminar;
    private javax.swing.JButton BTModificar;
    private javax.swing.JComboBox cbAntiguedad;
    private javax.swing.JComboBox cbSector;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaBusquedaDemandante;
    private javax.swing.JTextField textBusquedaDemandanteDNI;
    // End of variables declaration//GEN-END:variables
}
