/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.BolsaTrabajo;

import Vistas.BarraDeNavegacion;
import java.awt.CardLayout;

/**
 *
 * @author raul
 */
public class VistaBolsaTrabajo extends javax.swing.JPanel {

	public static String PanelInicio = "inicio";
	public static String PanelDemandaInicio = "demandasInicio";
	public static String PanelOfertasInicio = "ofertasInicio";
	public static String PanelConsultarOfertas = "consultarofertas";
	public static String PanelConsultarDemandas = "consultardemandas";
	public static String PanelNuevaDemanda = "nuevademanda";
	public static String PanelDatosOferta = "nuevaoferta";
	public static String PanelModificarDemanda = "modificardemanda";
	public static String PanelModificarOferta = "modificaroferta";
	public static String PanelBuscarDemandas = "buscardemandas";
	public static String PanelBuscarOfertas = "buscarofertas";

	/**
	 * Creates new form VistaBolsaTrabajo
	 */
	public VistaBolsaTrabajo() {
		initComponents();
	}

	public void showPanel (String panel) {
		CardLayout cardLayout =  (CardLayout)panelBolsaTrabajo.getLayout();
		cardLayout.show(panelBolsaTrabajo, panel);
	}

	public BarraDeNavegacion getBarraDeNavigacion() {
		return this.barraDeNavegacion;
	}

	public PanelBolsaTrabajoInicio getBolsaTrabajoInicio(){
		return this.panelBolsaTrabajoInicio;
	}

	public PanelConsultarDemanda getConsultarDemanda(){
		return this.panelConsultarDemanda;
	}

	public PanelDatosOferta getNuevaOferta(){
		return this.panelDatosOferta;
	}

	public PanelDemandanteBuscar getDemandanteBuscar(){
		return this.panelDemandanteBuscar;
	}

	public PanelDemandasInicio getDemandasInicio(){
		return this.panelDemandasInicio;
	}

	public PanelModificarDemanda getModificarDemanda(){
		return this.panelModificarDemanda;
	}

	public PanelNuevaDemanda getNuevaDemanda(){
		return this.panelNuevaDemanda;
	}

	public PanelOfertasBuscar getOfertasBuscar(){
		return this.panelOfertasBuscar;
	}

	public PanelOfertasInicio getOfertasInicio(){
		return this.panelOfertasInicio1;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeNavegacion = new Vistas.BarraDeNavegacion();
        panelBolsaTrabajo = new javax.swing.JPanel();
        panelConsultarDemanda = new Vistas.Paneles.BolsaTrabajo.PanelConsultarDemanda();
        panelDemandanteBuscar = new Vistas.Paneles.BolsaTrabajo.PanelDemandanteBuscar();
        panelModificarDemanda = new Vistas.Paneles.BolsaTrabajo.PanelModificarDemanda();
        panelNuevaDemanda = new Vistas.Paneles.BolsaTrabajo.PanelNuevaDemanda();
        panelDatosOferta = new Vistas.Paneles.BolsaTrabajo.PanelDatosOferta();
        panelOfertasBuscar = new Vistas.Paneles.BolsaTrabajo.PanelOfertasBuscar();
        panelDemandasInicio = new Vistas.Paneles.BolsaTrabajo.PanelDemandasInicio();
        panelOfertasInicio1 = new Vistas.Paneles.BolsaTrabajo.PanelOfertasInicio();
        panelBolsaTrabajoInicio = new Vistas.Paneles.BolsaTrabajo.PanelBolsaTrabajoInicio();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.BorderLayout());
        add(barraDeNavegacion, java.awt.BorderLayout.PAGE_START);

        panelBolsaTrabajo.setLayout(new java.awt.CardLayout());
        panelBolsaTrabajo.add(panelConsultarDemanda, "consultardemandas");
        panelBolsaTrabajo.add(panelDemandanteBuscar, "buscardemandas");
        panelBolsaTrabajo.add(panelModificarDemanda, "modificardemanda");
        panelBolsaTrabajo.add(panelNuevaDemanda, "nuevademanda");
        panelBolsaTrabajo.add(panelDatosOferta, "nuevaoferta");
        panelBolsaTrabajo.add(panelOfertasBuscar, "buscarofertas");
        panelBolsaTrabajo.add(panelDemandasInicio, "demandasInicio");
        panelBolsaTrabajo.add(panelOfertasInicio1, "ofertasInicio");
        panelBolsaTrabajo.add(panelBolsaTrabajoInicio, "inicio");

        add(panelBolsaTrabajo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.BarraDeNavegacion barraDeNavegacion;
    private javax.swing.JPanel panelBolsaTrabajo;
    private Vistas.Paneles.BolsaTrabajo.PanelBolsaTrabajoInicio panelBolsaTrabajoInicio;
    private Vistas.Paneles.BolsaTrabajo.PanelConsultarDemanda panelConsultarDemanda;
    private Vistas.Paneles.BolsaTrabajo.PanelDemandanteBuscar panelDemandanteBuscar;
    private Vistas.Paneles.BolsaTrabajo.PanelDemandasInicio panelDemandasInicio;
    private Vistas.Paneles.BolsaTrabajo.PanelModificarDemanda panelModificarDemanda;
    private Vistas.Paneles.BolsaTrabajo.PanelNuevaDemanda panelNuevaDemanda;
    private Vistas.Paneles.BolsaTrabajo.PanelDatosOferta panelDatosOferta;
    private Vistas.Paneles.BolsaTrabajo.PanelOfertasBuscar panelOfertasBuscar;
    private Vistas.Paneles.BolsaTrabajo.PanelOfertasInicio panelOfertasInicio1;
    // End of variables declaration//GEN-END:variables
}
