/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Empresa;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author PLB
 */
public class PanelEmpresaBuscar extends javax.swing.JPanel {

    /**
     * Creates new form PanelEmpresaBuscar
     */
    public PanelEmpresaBuscar() {
        initComponents();
        jLabelError.setVisible(false);
    }

    public JLabel getLabelError() {
        return jLabelError;
    }

    public void setTextLabelError(String text){
        jLabelError.setText(text);
        jLabelError.setVisible(true);
    }

    public JTextField getBuscarEmpresa(){
        return JtextBuscarEmpresa;
    }

    public String getTextBusquedaEmpresa() {
        return JtextBuscarEmpresa.getText();
    }

    public String getTipoDatoBusquedaEmpresa() {
        return cbTipoBusquedaEmpresa.getSelectedItem().toString();
    }

    public JButton getBtConsultarEmpresa(){
        return btConsultarEmpresa;
    }

    public JButton getBtEliminarEmpresa(){
        return btEliminarEmpresa;
    }

    public JButton getBtBuscarEmpresa(){
        return btBuscarEmpresa;
    }

    public JTable getTbBuscadorEmpresas(){
        return tableBuscarEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtextBuscarEmpresa = new javax.swing.JTextField();
        jLabelBuscarPor = new javax.swing.JLabel();
        cbTipoBusquedaEmpresa = new javax.swing.JComboBox();
        btBuscarEmpresa = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        tableBuscarEmpresa = new javax.swing.JTable();
        btConsultarEmpresa = new javax.swing.JButton();
        btEliminarEmpresa = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelBuscarPor.setText("Buscar por:");

        cbTipoBusquedaEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CIF", "Nombre", "DireccionWeb" }));

        btBuscarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/buscar.png"))); // NOI18N

        tableBuscarEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIF", "Nombre", "DireccionWeb", "Localidad", "Fax"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane20.setViewportView(tableBuscarEmpresa);

        btConsultarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/modificar.png"))); // NOI18N

        btEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/borrar.png"))); // NOI18N

        jLabelError.setText("Mensaje de Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane20)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultarEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(btEliminarEmpresa)
                        .addGap(505, 505, 505))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBuscarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoBusquedaEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JtextBuscarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarEmpresa)
                        .addContainerGap(701, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JtextBuscarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btBuscarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarPor)
                    .addComponent(cbTipoBusquedaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConsultarEmpresa)
                    .addComponent(btEliminarEmpresa))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextBuscarEmpresa;
    private javax.swing.JButton btBuscarEmpresa;
    private javax.swing.JButton btConsultarEmpresa;
    private javax.swing.JButton btEliminarEmpresa;
    private javax.swing.JComboBox cbTipoBusquedaEmpresa;
    private javax.swing.JLabel jLabelBuscarPor;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JTable tableBuscarEmpresa;
    // End of variables declaration//GEN-END:variables
}
