/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles.Empresa;

import Vistas.Paneles.Empresa.*;
import Vistas.BarraDeNavegacion;
import java.awt.CardLayout;

/**
 *
 * @author raphaelcolleau
 */
public class VistaEmpresa extends javax.swing.JPanel {

    /* identificador de los paneles en el CardLayout */
    public static String panelInicio = "inicio";
    public static String panelBuscar = "buscar";
    public static String panelDatos = "datos";



    /**
     * Creates new form PanelVoluntario
     */
    public VistaEmpresa() {
        initComponents();
    }

    // getter panel
    public BarraDeNavegacion getBarraDeNavegacion() {
        //System.out.println("Barra de navegacion Vista socio");
        return barraDeNavegacion;
    }

    public PanelEmpresaInicio getPanelEmpresaInicio() {
        System.out.println("Panel socio inico vista socio datos");
        return panelEmpresaInicio;
    }

    public PanelEmpresaDatos getPanelEmpresaDatos() {
        return panelEmpresaDatos;
    }

    public PanelEmpresaBuscar getPanelEmpresaBuscar() {
        return panelEmpresaBuscar;
    }

    // mostrar un panel con el CardLayoud
    public void showPanel (String panel) {
        CardLayout cardLayout =  (CardLayout)panelEmpresa.getLayout();
        cardLayout.show(panelEmpresa, panel);
        System.out.println("ShowPanel vista Socio"); 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeNavegacion = new Vistas.BarraDeNavegacion();
        panelEmpresa = new javax.swing.JPanel();
        panelEmpresaInicio = new Vistas.Paneles.Empresa.PanelEmpresaInicio();
        panelEmpresaDatos = new Vistas.Paneles.Empresa.PanelEmpresaDatos();
        panelEmpresaBuscar = new Vistas.Paneles.Empresa.PanelEmpresaBuscar();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.BorderLayout());

        barraDeNavegacion.setAlignmentX(10.0F);
        add(barraDeNavegacion, java.awt.BorderLayout.PAGE_START);

        panelEmpresa.setMaximumSize(new java.awt.Dimension(1000, 550));
        panelEmpresa.setMinimumSize(new java.awt.Dimension(1000, 550));
        panelEmpresa.setPreferredSize(new java.awt.Dimension(1000, 550));
        panelEmpresa.setLayout(new java.awt.CardLayout());
        panelEmpresa.add(panelEmpresaInicio, "empresaInicio");
        panelEmpresa.add(panelEmpresaDatos, "empresaDatos");
        panelEmpresa.add(panelEmpresaBuscar, "empresaBuscar");

        add(panelEmpresa, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.BarraDeNavegacion barraDeNavegacion;
    private javax.swing.JPanel panelEmpresa;
    private Vistas.Paneles.Empresa.PanelEmpresaBuscar panelEmpresaBuscar;
    private Vistas.Paneles.Empresa.PanelEmpresaDatos panelEmpresaDatos;
    private Vistas.Paneles.Empresa.PanelEmpresaInicio panelEmpresaInicio;
    // End of variables declaration//GEN-END:variables

}
